version: '3'

services:
  mongo-account:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: account
      MONGO_INITDB_ROOT_PASSWORD: account
    networks:
      - account
  mongo-account-history:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: account
      MONGO_INITDB_ROOT_PASSWORD: account
    networks:
    - account
  account-service:
    build: ./account-service
    restart: always
    ports:
    - "8080:8080"
    depends_on:
      - mongo-account
    networks:
      - account
      - moneytracker
  account-history-service:
    build: ./account-history-service
    restart: always
    ports:
    - "8090:8090"
    depends_on:
      - mongo-account-history
    networks:
      - moneytracker
      - account-history

networks:
  account:
  account-history:
  moneytracker: