version: '3'

services:
  mongo-account:
    image: mongo
    restart: always
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: account
      MONGO_INITDB_ROOT_PASSWORD: account
    networks:
      - account
  account-service:
    build: ./account-service
    restart: always
    ports:
    - "8080:8080"
    depends_on:
      - mongo-account
    networks:
      - account
      - moneytracker

networks:
  account:
  moneytracker: