version: '3'

services:
  mongo-account:
    image: mongo
    restart: always
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: account
      MONGO_INITDB_ROOT_PASSWORD: account
    networks:
      - account

networks:
  account:
  moneytracker: